#!/usr/bin/env bash

set -Eeuo pipefail
# trap 'error "Command failed at line $LINENO"' ERR # Debug

source "${BASH_SOURCE%/*}/../libexec/devbox-utils"

inserted_start="# >>> autojump initialize >>>"
inserted_end="# <<< autojump initialize <<<"

install_autojump() {
  git clone https://github.com/wting/autojump.git
  cd autojump
  ./install.py -f
  cd ..
  rm -rf autojump
}

configure_autojump() {
  local content='[[ -s "${HOME}/.autojump/etc/profile.d/autojump.sh" ]] && source "${HOME}/.autojump/etc/profile.d/autojump.sh"'
  local rc_file=$1

  # Check if the marker already exists
  if grep -q "$inserted_start" "$rc_file"; then
    detect_sed
    # If the marker exists, replace the content between markers
    "$SED" -i --follow-symlinks \
      "/$inserted_start/,/$inserted_end/c\\$inserted_start\n$content\n$inserted_end" \
      "$rc_file"
  else
    # If no marker exists, append the content with markers
    {
      echo -e "\n$inserted_start\n$content\n$inserted_end\n"
    } >>"$rc_file"
  fi

  return
}

info "Installing autojump..."
if [ -d "${HOME}/.autojump" ]; then
  warning "${HOME}/.autojump already exists, skipping installation."
else
  info "Installing autojump from source to ${HOME}/.autojump"
  install_autojump
fi

info "Configuring autojump..."
configure_autojump "${HOME}/.zshrc"
configure_autojump "${HOME}/.bashrc"

printf " All processes are successfully completed 🎉\n"
