#!/usr/bin/env bash

declare -A osInfo
osInfo[/etc/redhat-release]=yum
osInfo[/etc/arch-release]=pacman
osInfo[/etc/gentoo-release]=emerge
osInfo[/etc/SuSE-release]=zypp
osInfo[/etc/debian_version]=apt-get
osInfo[/etc/alpine-release]=apk

# Determine linux distribution
for f in "${!osInfo[@]}"
do
  if [[ -f $f ]];then
      pkg_manager=${osInfo[$f]}
  fi
done

case "$pkg_manager" in
  apt-get)
    sudo apt-get update

    sudo apt-get install -y zsh rsync tmux aria2 nano git-lfs

    # System monitoring
    sudo apt-get install -y nvtop htop speedometer atop

    # Required by some LSP server for neovim
    sudo apt-get install -y npm python3-venv

    ;;
  *)
    echo "Distribution not supported."
    ;;
esac
