#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../libexec/devbox-utils"

install_miniconda() {
  mkdir -p "${HOME}/miniconda3"
  wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O "${HOME}/miniconda3/miniconda.sh"
  bash "${HOME}/miniconda3/miniconda.sh" -b -u -p "${HOME}/miniconda3"
  rm -rf "${HOME}/miniconda3/miniconda.sh"
}

initialize_miniconda() {
  "${HOME}/miniconda3/bin/conda" init $@
}

# Install Miniconda
info "Installing Miniconda..."
if [ -d "${HOME}/miniconda3" ]; then
  warning "${HOME}/miniconda3 already exists, skipping installation."
else
  install_miniconda
  success "Miniconda installation complete."
fi

# Shell env
info "Initializing Miniconda for your shell (bash and zsh)..."
initialize_miniconda bash zsh

# Completion
success "Conda setup complete."
