#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../libexec/devbox-utils"

function nvim_install_linux() {
  # Download the latest pre-built Neovim binaries and install them under /opt/nvim
  curl -LO --progress-bar https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
  sudo rm -rf /opt/nvim
  sudo tar -C /opt --transform='s/^nvim-linux-x86_64/nvim/' -xzf nvim-linux-x86_64.tar.gz
  rm nvim-linux-x86_64.tar.gz # Cleanup
}

function nvim_configure_linux() {
  # Update the given shell rc file to add Neovim's bin directory to PATH
  local content='export PATH="$PATH:/opt/nvim/bin"'
  local rc_file=$1

  configure_rc_block \
    "$rc_file" \
    "# >>> nvim initialize >>>" \
    "# <<< nvim initialize <<<" \
    "$content"
}

case "$(uname)" in
Linux*)
  info "Installing Neovim for Linux..."
  nvim_install_linux

  info "Configuring PATH for Neovim..."
  # Configure both Bash and Zsh rc files to include Neovim in PATH
  nvim_configure_linux ~/.bashrc
  nvim_configure_linux ~/.zshrc
  success "Neovim installation and configuration complete."
  ;;
Darwin*)
  info "Installing Neovim for MacOS via brew..."
  brew install neovim
  success "Neovim installation complete."
  ;;
*)
  error "Unsupported OS: $(uname)"
  ;;
esac

