#!/bin/bash

source "${BASH_SOURCE%/*}/../libexec/devbox-utils"

setup_ssh() {
  local PORT="$1"

  if [ ! -d ~/.ssh ]; then
    mkdir ~/.ssh
  fi
  cd ~/.ssh || return 1

  info "Generating SSH host RSA key..."
  ssh-keygen -t rsa -b 4096 -f ssh_host_rsa_key -N ""

  # sshd re-exec requires execution with an absolute path
  info "Starting sshd on port ${PORT}..."
  /usr/sbin/sshd -h ~/.ssh/ssh_host_rsa_key -p "${PORT}"

  success "SSH server is running on port ${PORT}"
}

# Ensure port argument is valid
if ! [[ "$1" =~ ^[0-9]+$ ]] || [ "$1" -lt 1024 ] || [ "$1" -gt 65535 ]; then
  error "Invalid port number. Please provide a port number between 1024 and 65535."
  exit 1
fi

setup_ssh "$1"
