#!/usr/bin/env bash
# Summary: Run devbox setup scripts
# Usage: devbox setup -l|--list
#        devbox setup <script_name> [<args>]

set -e

source "${BASH_SOURCE%/*}/../libexec/devbox-utils"

[ -n "$DEVBOX_DEBUG" ] && set -x

setup_dir="${DEVBOX_ROOT}/setup"

if [ -d "$setup_dir" ]; then
  setup_dir="$(realpath "$setup_dir")"
fi

# Discover setup scripts
shopt -s dotglob nullglob
setup_scripts=("$setup_dir"/*)
script_names=("${setup_scripts[@]##*/}")
shopt -u dotglob nullglob

# Provide devbox completions
case "$1" in
--complete)
  printf "%s\n" "${script_names[@]}"
  exit
  ;;
--list | -l)
  info "Finding script in: ${setup_dir}"
  success "Available setup scripts:"
  printf " - %s\n" "${script_names[@]}"
  exit
  ;;
-*)
  devbox-help --usage setup >&2
  exit 1
  ;;
*)
  SCRIPT_NAME=$1
  shift
  ;;
esac

if [ -f "${setup_dir}/${SCRIPT_NAME}" ]; then
  "${setup_dir}/${SCRIPT_NAME}" "$@"
else
  info "Finding script in: ${setup_dir}"
  error "Setup script not found: ${SCRIPT_NAME}"
fi
