#!/usr/bin/env bash

# Colors
RED='\033[0;31m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m' # No Color

info() {
  printf "${BLUE}==>${NC} ${BOLD}%s${NC}\n" "$1"
}

warning() {
  printf "${YELLOW}Warning:${NC} %s\n" "$1"
}

error() {
  printf "${RED}Error:${NC} %s\n" "$1"
}

success() {
  printf "${GREEN}==>${NC} ${BOLD}%s${NC}\n" "$1"
}
